import Head from 'next/head'
import FloatBtn from './FloatBtn';
import Footer from "./Footer";
import Header from "./Header";
import Menu from './Menu';
import Info from './Info';

export default function Layout({ children, title }) {
    return (
        <>
            <Head>
                <title>Emprender Publicidad | {title}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            {/* <Menu/> */}
            <Info />
            <Header />
            {children}
            <FloatBtn />
            <Footer />

        </>
    )
}